=== kitodo/kitodo-production/Kitodo-DataEditor/src/main/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!--
    This file provides an XML Schema for the ruleset. It was derived from the
    Java classes for parsing the ruleset. The structure and naming follow the
    the Java classes.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ruleset="http://names.kitodo.org/ruleset/v2"
           elementFormDefault="qualified"
           targetNamespace="http://names.kitodo.org/ruleset/v2">

    <xs:complexType name="AcquisitionStage">
        <xs:sequence>
            <xs:element name="setting" minOccurs="1" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="name"/>
    </xs:complexType>

    <xs:complexType name="CodomainElement">
        <xs:attribute type="ruleset:Type" name="type"/>
        <xs:attribute type="xs:anyURI" name="namespace"/>
    </xs:complexType>

    <xs:complexType name="DeclarationElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division" />
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Division">
        <xs:sequence>
            <xs:element type="ruleset:Label" minOccurs="1" maxOccurs="unbounded" name="label"/>
            <xs:element type="ruleset:SubdivisionByDateElement" minOccurs="0" maxOccurs="1" name="subdivisionByDate"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="xs:NMTOKEN" name="dates"/>
        <xs:attribute type="xs:string" name="scheme"/>
    </xs:complexType>

    <xs:simpleType name="DomainAttribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="description"/>
            <xs:enumeration value="digitalProvenance"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="technical"/>
            <xs:enumeration value="mets:div"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EditingElement">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
            <xs:element name="acquisitionStage" minOccurs="0" maxOccurs="unbounded" type="ruleset:AcquisitionStage"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Key">
        <xs:sequence>
            <xs:element name="label" minOccurs="1" maxOccurs="unbounded" type="ruleset:Label"/>
            <xs:element name="codomain" minOccurs="0" maxOccurs="1" type="ruleset:CodomainElement"/>
            <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            <xs:element name="pattern" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="preset" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="ruleset:DomainAttribute" name="domain" default="description"/>
    </xs:complexType>

    <xs:complexType name="Label">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="namespace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            </xs:sequence>
            <xs:attribute type="xs:anyURI" name="about"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="ruleset:Label"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="value"/>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence>
            <xs:element name="permit" minOccurs="0" maxOccurs="unbounded" type="ruleset:Rule"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="division"/>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs"/>
        <xs:attribute type="xs:nonNegativeInteger" name="maxOccurs"/>
        <xs:attribute type="ruleset:Unspecified" name="unspecified"/>
    </xs:complexType>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="declaration" minOccurs="1" maxOccurs="1" type="ruleset:DeclarationElement"/>
                <xs:element name="correlation" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="restriction" minOccurs="1" maxOccurs="unbounded" type="ruleset:Rule"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="editing" minOccurs="0" maxOccurs="1" type="ruleset:EditingElement"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="lang"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Setting">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:boolean" name="alwaysShowing" default="false"/>
        <xs:attribute type="xs:boolean" name="editable" default="true"/>
        <xs:attribute type="xs:boolean" name="excluded" default="false"/>
        <xs:attribute type="xs:boolean" name="multiline" default="false"/>
    </xs:complexType>

    <xs:complexType name="SubdivisionByDateElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division"/>
        </xs:sequence>
        <xs:attribute name="yearBegin">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="--((0[1-9]|1[0-2])-([01][1-9]|10|2[0-8]))|((0[13-9]|1[0-2])-(29|30))|((0[13578]|1[0-2])-31)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="anyURI"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Unspecified">
        <xs:restriction base="xs:string">
            <xs:enumeration value="unrestricted"/>
            <xs:enumeration value="forbidden"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== kitodo/kitodo-production/Kitodo/src/test/resources/rulesets/ruleset_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ../../../../../Kitodo-DataEditor/src/main/resources/ruleset.xsd">
    <declaration>
        <division id="Monograph" processTitle="TSL_ATS+'_'+CatalogIDDigital">
            <label>Monograph</label>
        </division>
        <division id="something">
            <label>Outline element</label>
        </division>
        <division id="ContainedWork" processTitle="TSL_ATS+'_'+CatalogIDDigital">
            <label>Beigefügtes Werk</label>
        </division>
        <division id="MultiVolumeWork" withWorkflow="false" processTitle="TSL_ATS+'_'+CatalogIDDigital"
                  use="createChildrenFromParent">
            <label>Mehrbändiges Werk</label>
        </division>
        <division id="Volume" withWorkflow="true" processTitle="TSL_ATS+'_'+CatalogIDDigital">
            <label>Band</label>
        </division>
        <key id="TitleDocMain" domain="source">
            <label>HauptTitel</label>
        </key>
        <key id="TitleDocMainShort" domain="technical">
            <label>Haupttitel (Sortierung)</label>
        </key>
        <key id="TSL_ATS">
            <label>TSL/ATS</label>
        </key>
        <key id="document_type" use="docType">
            <label>Document type</label>
        </key>
        <key id="CatalogIDDigital" use="recordIdentifier">
            <label>PPN (digital)</label>
        </key>
        <key id="CatalogIDSource" domain="source">
            <label>PPN (Vorlage)</label>
        </key>
        <key id="ContributorPerson">
            <label>Contributing Person (group)</label>
            <label lang="de">Mitwirkende Person (Gruppe)</label>
            <key id="LastName">
                <label>Last name</label>
                <label lang="de">Familienname</label>
            </key>
            <key id="RoleText">
                <label>Relationship designation (text)</label>
                <label lang="de">Beziehungskennzeichnung (Text)</label>
            </key>
            <key id="IdentifierPPN">
                <label>Identifier (PPN)</label>
                <label lang="de">Identifier (PPN)</label>
            </key>
            <key id="FirstName">
                <label>First name</label>
                <label lang="de">Vorname</label>
            </key>
            <key id="DisplayForm">
                <label>Display name</label>
                <label lang="de">Anzeigename</label>
            </key>
            <key id="RoleCode">
                <label>Relationship designation (code)</label>
                <label lang="de">Beziehungskennzeichnung (Code)</label>
            </key>
            <key id="Prefix">
                <label>Prefix</label>
                <label lang="de">Präfix</label>
            </key>
            <key id="Authority">
                <label>Authority</label>
                <label lang="de">Quelle (Normdaten)</label>
            </key>
            <key id="IdentifierGND">
                <label>Identifier (GND)</label>
                <label lang="de">Identifier (GND)</label>
            </key>
            <key id="IdentifierGNDURI">
                <label>GND-URI</label>
                <label lang="de">GND-URI</label>
            </key>
            <key id="PersonalName">
                <label>Personal name</label>
                <label lang="de">Persönlicher Name</label>
            </key>
            <key id="Count">
                <label>Count</label>
                <label lang="de">Zählung</label>
            </key>
            <key id="AdditionalMetadataPerson">
                <label>Surname, genus name, territory, title</label>
                <label lang="de">Beiname, Gattungsname, Territorium, Titulatur</label>
            </key>
        </key>
        <key id="Person">
            <label>Person</label>
            <key id="Role">
                <label>Rolle</label>
                <option value="Author">
                    <label>Autor</label>
                </option>
            </key>
            <key id="FirstName">
                <label>Vorname</label>
            </key>
            <key id="LastName">
                <label>Nachname</label>
            </key>
        </key>
    </declaration>
    <correlation>
        <restriction key="Person">
            <permit key="Role" minOccurs="1" maxOccurs="1"/>
            <permit key="FirstName"/>
            <permit key="LastName"/>
        </restriction>

        <restriction division="Monograph" unspecified="forbidden">
            <permit division="Monograph"/>
            <permit key="TitleDocMain" minOccurs="1"/>
            <permit key="TitleDocMainShort" minOccurs="1"/>
            <permit key="CatalogIDDigital" minOccurs="1"/>
            <permit key="CatalogIDSource" minOccurs="1"/>
            <permit key="TSL_ATS"/>
            <permit key="ContributorPerson"/>
            <permit key="Person">
                <permit key="Role" unspecified="forbidden">
                    <permit value="Author"/>
                </permit>
            </permit>
        </restriction>
        <restriction division="MultiVolumeWork" unspecified="forbidden">
            <permit division="Volume"/>
            <permit key="TitleDocMain" minOccurs="1"/>
            <permit key="TitleDocMainShort" minOccurs="1"/>
            <permit key="CatalogIDDigital" minOccurs="1"/>
            <permit key="CatalogIDSource" minOccurs="1"/>
            <permit key="TSL_ATS"/>
            <permit key="ContributorPerson"/>
        </restriction>
        <restriction division="ContainedWork" unspecified="forbidden">
                <permit key="TitleDocMain" minOccurs="1"/>
                <permit key="TitleDocMainShort" minOccurs="1"/>
                <permit key="CatalogIDDigital" minOccurs="1"/>
            <permit key="CatalogIDSource" minOccurs="1"/>
            <permit key="TSL_ATS"/>
        </restriction>
    </correlation>
    <editing>
        <setting key="TSL_ATS" alwaysShowing="true"/>
        <setting key="Person" alwaysShowing="true">
            <setting key="FirstName" alwaysShowing="true"/>
            <setting key="LastName" alwaysShowing="true"/>
        </setting>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testUnspecifiedUnrestrictedRulesSortDivisionsWithoutRestrictingThem.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="phonographicRecord">
            <label>Record</label>
        </division>
        <division id="article">
            <label>Article</label>
        </division>
        <division id="book">
            <label>Book</label>
        </division>
        <division id="cassette">
            <label>Cassette</label>
        </division>
        <division id="chalcography">
            <label>Chalcography</label>
        </division>
        <division id="cd">
            <label>CD</label>
        </division>
        <division id="serial">
            <label>Serial publication</label>
        </division>
        <division id="colorChart">
            <label>Color chart</label>
        </division>
        <division id="frontCover">
            <label>Front cover</label>
        </division>
        <division id="side">
            <label>Side</label>
        </division>
        <division id="box">
            <label>Box</label>
        </division>
        <division id="videoTape">
            <label>Video tape</label>
        </division>
        <division id="multiVolume">
            <label>Multi-volume work</label>
        </division>
        <division id="gramophoneRecord">
            <label>Gramophone record</label>
        </division>
        <division id="pianoRoll">
            <label>Piano roll</label>
        </division>
        <division id="dvd">
            <label>DVD</label>
        </division>
        <division id="wireRecording">
            <label>Wire recording</label>
        </division>
        <division id="film">
            <label>Motion picture film</label>
        </division>
    </declaration>
    <correlation>
        <restriction division="box">
            <permit division="phonographicRecord"/>
            <permit division="cassette"/>
            <permit division="cd"/>
            <permit division="gramophoneRecord"/>
            <permit division="pianoRoll"/>
        </restriction>
    </correlation>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testDivisionsSubdividedByDateReportDateSchemeAndField.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="playtime">
            <label>Playtime ‹complete edition›</label>
            <subdivisionByDate yearBegin="--08-01">
                <division id="playtimeYear" dates="ORDERLABEL" scheme="yyyy/yyyy">
                    <label>Year’s issues ‹playtime›</label>
                </division>
                <division id="playtimeMonth" dates="ORDERLABEL" scheme="yyyy-MM">
                    <label>Month’s issues ‹playtime›</label>
                </division>
                <division id="playtimeDay" dates="ORDERLABEL" scheme="yyyy-MM-dd">
                    <label>Day’s issues ‹playtime›</label>
                </division>
            </subdivisionByDate>
        </division>
        <key id="ORDERLABEL" domain="mets:div">
            <label>METS order label</label>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testCorrectValidationOfRegularExpressions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="defaultStringKey">
            <label>Default string key → PPN</label>
            <pattern>[0-9]{7,}[0-9X]</pattern>
        </key>
        <key id="anyURIKey">
            <label>anyURI key → WWW URL</label>
            <codomain type="anyURI"/>
            <pattern>https?://.+/.*</pattern>
        </key>
        <key id="booleanKey">
            <label>Boolean key</label>
            <codomain type="boolean"/>
            <option value="on"/>
            <preset>on</preset>
            <pattern>on</pattern>
        </key>
        <key id="dateKey">
            <label>Date key</label>
            <codomain type="date"/>
            <pattern>(19\d{2}|20[01]\d)-\d{2}-\d{2}</pattern>
        </key>
        <key id="integerKey">
            <label>Integer key</label>
            <codomain type="integer"/>
            <pattern>17\d{2}</pattern>
        </key>
        <key id="namespaceDefaultAnyURIKey">
            <label>Namespace default anyURI key</label>
            <codomain namespace="http://test.example/non-existent-namespace/"/>
            <pattern>^http://test.example/non-existent-namespace/[_A-Za-z][_0-9A-Za-z]*</pattern>
        </key>
        <key id="namespaceStringKey">
            <label>Namespace default anyURI key</label>
            <codomain type="string" namespace="http://test.example/non-existent-namespace/"/>
            <pattern>^http://test.example/non-existent-namespace/[_A-Za-z][_0-9A-Za-z]*</pattern>
        </key>
        <key id="optionsKey">
            <label>Options key</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
            <pattern>opt\d+</pattern>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testDisplaySettingsWithAcquisitionStage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="alwaysShowingUnchangedTrue">
            <label>Always showing unchanged/true</label>
        </key>
        <key id="alwaysShowingTrueUnchanged">
            <label>Always showing true/unchanged</label>
        </key>
        <key id="alwaysShowingTrueOtherchanges">
            <label>Always showing true/other changes</label>
        </key>
        <key id="alwaysShowingTrueTrue">
            <label>Always showing true/true</label>
        </key>
        <key id="alwaysShowingTrueFalse">
            <label>Always showing true/false</label>
        </key>
        <key id="excludedUnchangedTrue">
            <label>Excluded unchanged/true</label>
        </key>
        <key id="excludedTrueUnchanged">
            <label>Excluded true/unchanged</label>
        </key>
        <key id="excludedTrueOtherchanges">
            <label>Excluded true/other changes</label>
        </key>
        <key id="excludedTrueTrue">
            <label>Excluded true/true</label>
        </key>
        <key id="excludedTrueFalse">
            <label>Excluded true/false</label>
        </key>
        <key id="editableUnchangedFalse">
            <label>Editable unchanged/false</label>
        </key>
        <key id="editableFalseUnchanged">
            <label>Editable false/unchanged</label>
        </key>
        <key id="editableFalseOtherchanges">
            <label>Editable false/other changes</label>
        </key>
        <key id="editableFalseFalse">
            <label>Editable false/false</label>
        </key>
        <key id="editableFalseTrue">
            <label>Editable false/true</label>
        </key>
        <key id="multilineUnchangedTrue">
            <label>Multi-line unchanged/true</label>
        </key>
        <key id="multilineTrueUnchanged">
            <label>Multi-line true/unchanged</label>
        </key>
        <key id="multilineTrueOtherchanges">
            <label>Multi-line true/other changes</label>
        </key>
        <key id="multilineTrueTrue">
            <label>Multi-line true/true</label>
        </key>
        <key id="multilineTrueFalse">
            <label>Multi-line true/false</label>
        </key>
    </declaration>
    <editing>
        <setting key="alwaysShowingTrueUnchanged" alwaysShowing="true"/>
        <setting key="alwaysShowingTrueOtherchanges" alwaysShowing="true"/>
        <setting key="alwaysShowingTrueTrue" alwaysShowing="true"/>
        <setting key="alwaysShowingTrueFalse" alwaysShowing="true"/>
        <setting key="excludedTrueUnchanged" excluded="true"/>
        <setting key="excludedTrueOtherchanges" excluded="true"/>
        <setting key="excludedTrueTrue" excluded="true"/>
        <setting key="excludedTrueFalse" excluded="true"/>
        <setting key="editableFalseUnchanged" editable="false"/>
        <setting key="editableFalseOtherchanges" editable="false"/>
        <setting key="editableFalseFalse" editable="false"/>
        <setting key="editableFalseTrue" editable="false"/>
        <setting key="multilineTrueUnchanged" multiline="true"/>
        <setting key="multilineTrueOtherchanges" multiline="true"/>
        <setting key="multilineTrueTrue" multiline="true"/>
        <setting key="multilineTrueFalse" multiline="true"/>
        <acquisitionStage name="The acquisition stage">
            <setting key="alwaysShowingUnchangedTrue" alwaysShowing="true"/>
            <setting key="alwaysShowingTrueOtherchanges" multiline="true"/>
            <setting key="alwaysShowingTrueTrue" alwaysShowing="true"/>
            <setting key="alwaysShowingTrueFalse" alwaysShowing="false"/>
            <setting key="excludedUnchangedTrue" excluded="true"/>
            <setting key="excludedTrueOtherchanges" multiline="true"/>
            <setting key="excludedTrueTrue" excluded="true"/>
            <setting key="excludedTrueFalse" excluded="false"/>
            <setting key="editableUnchangedFalse" editable="false"/>
            <setting key="editableFalseOtherchanges" multiline="true"/>
            <setting key="editableFalseFalse" editable="false"/>
            <setting key="editableFalseTrue" editable="true"/>
            <setting key="multilineUnchangedTrue" multiline="true"/>
            <setting key="multilineTrueOtherchanges" alwaysShowing="true"/>
            <setting key="multilineTrueTrue" multiline="true"/>
            <setting key="multilineTrueFalse" multiline="false"/>
        </acquisitionStage>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testTheDisplayModeIsSetUsingTheCodomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="defaultString">
            <label>String (default)</label>
        </key>
        <key id="anyURI">
            <label>Any URI</label>
            <codomain type="anyURI"/>
        </key>
        <key id="boolean">
            <label>Boolean</label>
            <codomain type="boolean"/>
            <option value="on"/>
        </key>
        <key id="date">
            <label>Date</label>
            <codomain type="date"/>
        </key>
        <key id="integer">
            <label>Integer</label>
            <codomain type="integer"/>
        </key>
        <key id="namespace">
            <label>Namespace (default)</label>
            <codomain namespace="http://nowhere.example/namespace-example#"/>
        </key>
        <key id="namespaceString">
            <label>Namespace (String)</label>
            <codomain type="string" namespace="http://nowhere.example/namespace-example#"/>
        </key>
    </declaration>
</ruleset>
