=== kitodo/kitodo-production/Kitodo-DataEditor/src/main/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!--
    This file provides an XML Schema for the ruleset. It was derived from the
    Java classes for parsing the ruleset. The structure and naming follow the
    the Java classes.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ruleset="http://names.kitodo.org/ruleset/v2"
           elementFormDefault="qualified"
           targetNamespace="http://names.kitodo.org/ruleset/v2">

    <xs:complexType name="AcquisitionStage">
        <xs:sequence>
            <xs:element name="setting" minOccurs="1" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="name"/>
    </xs:complexType>

    <xs:complexType name="CodomainElement">
        <xs:attribute type="ruleset:Type" name="type"/>
        <xs:attribute type="xs:anyURI" name="namespace"/>
    </xs:complexType>

    <xs:complexType name="DeclarationElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division" />
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Division">
        <xs:sequence>
            <xs:element type="ruleset:Label" minOccurs="1" maxOccurs="unbounded" name="label"/>
            <xs:element type="ruleset:SubdivisionByDateElement" minOccurs="0" maxOccurs="1" name="subdivisionByDate"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="xs:NMTOKEN" name="dates"/>
        <xs:attribute type="xs:string" name="scheme"/>
    </xs:complexType>

    <xs:simpleType name="DomainAttribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="description"/>
            <xs:enumeration value="digitalProvenance"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="technical"/>
            <xs:enumeration value="mets:div"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EditingElement">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
            <xs:element name="acquisitionStage" minOccurs="0" maxOccurs="unbounded" type="ruleset:AcquisitionStage"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Key">
        <xs:sequence>
            <xs:element name="label" minOccurs="1" maxOccurs="unbounded" type="ruleset:Label"/>
            <xs:element name="codomain" minOccurs="0" maxOccurs="1" type="ruleset:CodomainElement"/>
            <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            <xs:element name="pattern" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="preset" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="ruleset:DomainAttribute" name="domain" default="description"/>
    </xs:complexType>

    <xs:complexType name="Label">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="namespace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            </xs:sequence>
            <xs:attribute type="xs:anyURI" name="about"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="ruleset:Label"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="value"/>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence>
            <xs:element name="permit" minOccurs="0" maxOccurs="unbounded" type="ruleset:Rule"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="division"/>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs"/>
        <xs:attribute type="xs:nonNegativeInteger" name="maxOccurs"/>
        <xs:attribute type="ruleset:Unspecified" name="unspecified"/>
    </xs:complexType>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="declaration" minOccurs="1" maxOccurs="1" type="ruleset:DeclarationElement"/>
                <xs:element name="correlation" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="restriction" minOccurs="1" maxOccurs="unbounded" type="ruleset:Rule"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="editing" minOccurs="0" maxOccurs="1" type="ruleset:EditingElement"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="lang"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Setting">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:boolean" name="alwaysShowing" default="false"/>
        <xs:attribute type="xs:boolean" name="editable" default="true"/>
        <xs:attribute type="xs:boolean" name="excluded" default="false"/>
        <xs:attribute type="xs:boolean" name="multiline" default="false"/>
    </xs:complexType>

    <xs:complexType name="SubdivisionByDateElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division"/>
        </xs:sequence>
        <xs:attribute name="yearBegin">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="--((0[1-9]|1[0-2])-([01][1-9]|10|2[0-8]))|((0[13-9]|1[0-2])-(29|30))|((0[13578]|1[0-2])-31)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="anyURI"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Unspecified">
        <xs:restriction base="xs:string">
            <xs:enumeration value="unrestricted"/>
            <xs:enumeration value="forbidden"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testUnspecifiedUnrestrictedRulesSortKeysWithoutRestrictingThem.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="article">
            <label>Article</label>
        </division>
        <key id="abstract">
            <label>Abstract</label>
        </key>
        <key id="author">
            <label>Author</label>
            <key id="city">
                <label>City</label>
            </key>
            <key id="dept">
                <label>Department</label>
            </key>
            <key id="firstName">
                <label>First name</label>
            </key>
            <key id="institution">
                <label>Institution</label>
            </key>
            <key id="lastName">
                <label>Last name</label>
            </key>
            <key id="notes">
                <label>Notes</label>
            </key>
        </key>
        <key id="issue">
            <label>Issue</label>
            <codomain type="integer" />
        </key>
        <key id="journal">
            <label>Journal title</label>
        </key>
        <key id="journalAbbr">
            <label>Journal title abbreviated</label>
        </key>
        <key id="title">
            <label>Title</label>
        </key>
        <key id="year">
            <label>Publication year</label>
        </key>
    </declaration>
    <correlation>
        <restriction division="article">
            <permit key="author"/>
            <permit key="year"/>
            <permit key="title"/>
            <permit key="journal"/>
            <permit key="journalAbbr"/>
            <permit key="issue"/>
        </restriction>
        <restriction key="author">
            <permit key="lastName"/>
            <permit key="firstName"/>
            <permit key="dept"/>
            <permit key="institution"/>
            <permit key="city"/>
        </restriction>
    </correlation>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testCorrectReturnOfOptions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="mandatoryMultiLineSingleSelection">
            <label>Mandatory multi-line single selection</label>
            <option value="dan">
                <label>Danish</label>
                <label lang="de">Dänisch</label>
            </option>
            <option value="dut">
                <label>Dutch</label>
                <label lang="de">Niederländisch</label>
            </option>
            <option value="eng">
                <label>English</label>
                <label lang="de">Englisch</label>
            </option>
            <option value="fre">
                <label>French</label>
                <label lang="de">Französisch</label>
            </option>
            <option value="ger">
                <label>German</label>
                <label lang="de">Deutsch</label>
            </option>
        </key>
        <key id="mandatoryOneLineSingleSelection">
            <label>Mandatory one-line single selection</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
        <key id="mandatoryMultipleSelection">
            <label>Multiple selection</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
        <key id="optionalMultipleSelection">
            <label>Multiple selection</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
        <key id="optionalMultiLineSingleSelection">
            <label>Optional multi-line single selection</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
        <key id="optionalOneLineSingleSelection">
            <label>Optional one-line single selection</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
    </declaration>
    <correlation>
        <restriction division="book">
            <permit key="mandatoryMultiLineSingleSelection" minOccurs="1" maxOccurs="1"/>
            <permit key="mandatoryOneLineSingleSelection" minOccurs="1" maxOccurs="1"/>
            <permit key="mandatoryMultipleSelection" minOccurs="1"/>
            <permit key="optionalMultiLineSingleSelection" maxOccurs="1"/>
            <permit key="optionalOneLineSingleSelection" maxOccurs="1"/>
        </restriction>
    </correlation>
    <editing>
        <setting key="mandatoryMultiLineSingleSelection" multiline="true"/>
        <setting key="optionalMultiLineSingleSelection" multiline="true"/>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testDivisionsAreCorrectlyTranslated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!-- For example, perhaps the simplest variant of a rule set might look like this.
     It has only the declaration section. With this rule set only books
     can be cataloged. For each book author, year, title, publisher and place
     of publication can be recorded. Otherwise there are no further
     requirements. -->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
            <label lang="de">Buch</label>
            <label lang="fr">Livre</label>
        </division>
        <key id="publicationYear">
            <label>Publication year</label>
            <codomain type="integer"/>
        </key>
        <key id="language">
            <label>Language</label>
            <codomain namespace="http://id.loc.gov/vocabulary/iso639-2/"/>
        </key>
        <key id="titleDocMain">
            <label>Main title</label>
        </key>
        <key id="publisherName">
            <label>Publisher</label>
        </key>
        <key id="placeOfPublication">
            <label>Place of publication</label>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testValidationByCodomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="default">
            <label>Default</label>
        </key>
        <key id="defaultOpt">
            <label>Default</label>
            <option value="val1"/>
            <option value="val2"/>
            <option value="val3"/>
        </key>
        <key id="anyUri">
            <label>Any URI</label>
            <codomain type="anyURI"/>
        </key>
        <key id="boolean">
            <label>Boolean</label>
            <codomain type="boolean"/>
            <option value="on"/>
        </key>
        <key id="date">
            <label>Date</label>
            <codomain type="date"/>
        </key>
        <key id="integer">
            <label>Integer</label>
            <codomain type="integer"/>
        </key>
        <key id="namespaceDefault">
            <label>Namespace default, external</label>
            <codomain namespace="http://test.example/testValidation/"/>
        </key>
        <key id="namespaceString">
            <label>Namespace string</label>
            <codomain type="string" namespace="http://test.example/testValidation/"/>
        </key>
        <key id="namespaceDefaultOpt">
            <label>Namespace default with options</label>
            <codomain namespace="http://test.example/testValidation/"/>
            <option value="http://test.example/testValidation/value1"/>
            <option value="http://test.example/testValidation/value2"/>
            <option value="http://test.example/testValidation/value3"/>
        </key>
        <key id="namespaceStringOpt">
            <label>Namespace string with options</label>
            <codomain type="string" namespace="http://test.example/testValidation/"/>
            <option value="http://test.example/testValidation/value1"/>
            <option value="http://test.example/testValidation/value2"/>
            <option value="http://test.example/testValidation/value3"/>
        </key>
        <key id="namespaceDefaultExternal">
            <label>Namespace default external</label>
            <codomain namespace="http://test.example/testValidationByCodomainNamespace"/>
        </key>
        <key id="namespaceStringExternal">
            <label>Namespace string external</label>
            <codomain type="string" namespace="http://test.example/testValidationByCodomainNamespace#"/>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testDivisionsSubdividedByDateHaveOnlyTheCorrectChildren.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="newspaper" processTitle="shelfMark">
            <label>Newspaper ‹complete edition›</label>
            <label lang="de">Zeitung ‹Gesamtausgabe›</label>
            <subdivisionByDate>
                <division id="newspaperYear" dates="ORDERLABEL"
                    scheme="yyyy" processTitle="shelfMark+'_'+#YEAR">
                    <label>Year’s issues ‹newspaper›</label>
                    <label lang="de">Jahrgang ‹Zeitung›</label>
                </division>
                <division id="newspaperMonth" dates="ORDERLABEL" scheme="M"
                    processTitle="shelfMark+'_'+#YEAR+#MONTH+#DAY+#ISSU">
                    <label>Month’s issues ‹newspaper›</label>
                    <label lang="de">Monat ‹Zeitung›</label>
                </division>
                <division id="newspaperDay" dates="ORDERLABEL"
                    scheme="d">
                    <label>Day’s issues ‹newspaper›</label>
                    <label lang="de">Tag ‹Zeitung›</label>
                </division>
            </subdivisionByDate>
        </division>
        <division id="newspaperLimitedTest" processTitle="shelfMark">
            <label>Newspaper ‹complete edition›—limited test</label>
            <subdivisionByDate>
                <division id="newspaperYearLimitedTest" dates="ORDERLABEL"
                    scheme="yyyy" processTitle="shelfMark+'_'+#YEAR">
                    <label>Year’s issues ‹newspaper›—limited test</label>
                </division>
                <division id="newspaperMonthLimitedTest" dates="ORDERLABEL" scheme="M"
                    processTitle="shelfMark+'_'+#YEAR+#MONTH+#DAY+#ISSU">
                    <label>Month’s issues ‹newspaper›—limited test</label>
                </division>
                <division id="newspaperDayLimitedTest" dates="ORDERLABEL" scheme="d">
                    <label>Day’s issues ‹newspaper›—limited test</label>
                </division>
            </subdivisionByDate>
        </division>
        <division id="newspaperIssue">
            <label>Issue ‹newspaper›</label>
            <label lang="de">Ausgabe ‹Zeitung›</label>
        </division>
        <key id="ORDERLABEL" domain="mets:div">
            <label>METS order label</label>
            <label lang="de">METS Reihenfolge-Etikett</label>
        </key>
    </declaration>
    <correlation>
        <restriction division="newspaperDayLimitedTest" unspecified="forbidden">
            <permit division="newspaperIssue"/>
        </restriction>
    </correlation>
</ruleset>

=== kitodo/kitodo-production/Kitodo/src/test/resources/rulesets/simple-book.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!-- An example how the perhaps simplest variant of a rule set might look like.
     It has only the declaration section. With this rule set, only books
     can be described. For each book author, year, title, publisher and place
     of publication can be recorded.
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
            <label lang="de">Buch</label>
            <label lang="fr">Livre</label>
        </division>
        <key id="document_type" use="docType">
            <label>Document type</label>
        </key>
        <key id="publicationYear">
            <label>Publication year</label>
            <codomain type="integer"/>
        </key>
        <key id="language">
            <label>Language</label>
            <!--<codomain namespace="http://id.loc.gov/vocabulary/iso639-2/"/>-->
            <option value="de"><label>Deutsch</label></option>
            <option value="fr"><label>Franz√∂sisch</label></option>
        </key>
        <key id="titleDocMain" use="structureTreeTitle">
            <label>Main title</label>
        </key>
        <key id="publisherName">
            <label>Publisher</label>
        </key>
        <key id="placeOfPublication">
            <label>Place of publication</label>
        </key>
        <key id="person">
            <label lang="de">Person (Gruppe)</label>
            <label lang="en">Person (Group)</label>
            <key id="RoleCode">
                <label>Relationship designation (code)</label>
                <label lang="de">Beziehungskennzeichnung (Code)</label>
                <option value="pht"><label>Fotograf</label></option>
                <option value="edt"><label>Herausgeber</label></option>
                <option value="aut"><label>Verfasser</label></option>
            </key>
        </key>
    </declaration>
    <correlation>
        <restriction division="book">
            <permit key="person" minOccurs="1"/>
        </restriction>
        <restriction key="person">
            <permit key="RoleCode" minOccurs="1"/>
        </restriction>
    </correlation>
    <editing>
        <setting key="language" filterable="true"/>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo/src/test/resources/rulesets/ImportProcessesIT.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ../../../../rulesets/ruleset.xsd"
>
    <!-- metadata definition -->
    <declaration>
        <!-- parent -->
        <division id="case" processTitle="CRNumber+'_'+CaseNumber">
            <label>Case</label>
        </division>

        <!-- children -->
        <division id="assignment" processTitle="+'_'+DocumentNumber">
            <label>Assignment</label>
        </division>
        <division id="budget" processTitle="+'_'+DocumentNumber">
            <label>Budget</label>
        </division>

        <!-- metadata -->
        <key id="Address">
            <label>Address</label>
            <key id="StreetName">
                <label>Street</label>
            </key>
            <key id="HouseNumber">
                <label>House no.</label>
            </key>
            <key id="Additions">
                <label>House number supplement</label>
            </key>
        </key>
        <key id="CaseNumber">
            <label>Case no.</label>
            <codomain type="integer"/>
            <pattern>[1-9]\d*</pattern>
        </key>
        <key id="CRNumber">
            <label>Area code</label>
            <codomain type="integer"/>
            <pattern>[1-9]\d{0,4}</pattern>
        </key>
        <key id="DocumentNumber">
            <label>Document no.</label>
            <pattern>\d{4}</pattern>
        </key>
        <key id="DocumentNameFree">
            <label>Document name</label>
        </key>
        <key id="DocumentDate">
            <label>Date</label>
        </key>
    </declaration>

    <!-- metadata validation -->
    <correlation>
        <!-- valid grouped metadata -->
        <restriction key="Address">
            <permit key="StreetName" minOccurs="1" maxOccurs="1"/>
            <permit key="HouseNumber" minOccurs="1" maxOccurs="1"/>
            <permit key="Additions" maxOccurs="1"/>
        </restriction>

        <!-- valid parent -->
        <restriction division="case" unspecified="forbidden">
            <permit division="assignment"/>
            <permit division="budget"/>
            <permit key="CRNumber" minOccurs="1" maxOccurs="1"/>
            <permit key="CaseNumber" minOccurs="1" maxOccurs="1"/>
            <permit key="Description1" minOccurs="1" maxOccurs="1"/>
            <permit key="Address"/>
        </restriction>

        <!-- valid children -->
        <restriction division="assignment" unspecified="forbidden">
            <permit key="DocumentNumber" minOccurs="1" maxOccurs="1"/>
            <permit key="DocumentNameFree" minOccurs="1" maxOccurs="1"/>
            <permit key="DocumentDate" minOccurs="1" maxOccurs="1"/>
        </restriction>

        <restriction division="budget" unspecified="forbidden">
            <permit key="DocumentNumber" minOccurs="1" maxOccurs="1"/>
            <permit key="DocumentNameFree" minOccurs="1" maxOccurs="1"/>
            <permit key="DocumentDate" minOccurs="1" maxOccurs="1"/>
        </restriction>
    </correlation>
</ruleset>
