=== kitodo/kitodo-production/Kitodo-DataEditor/src/main/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!--
    This file provides an XML Schema for the ruleset. It was derived from the
    Java classes for parsing the ruleset. The structure and naming follow the
    the Java classes.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ruleset="http://names.kitodo.org/ruleset/v2"
           elementFormDefault="qualified"
           targetNamespace="http://names.kitodo.org/ruleset/v2">

    <xs:complexType name="AcquisitionStage">
        <xs:sequence>
            <xs:element name="setting" minOccurs="1" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="name"/>
    </xs:complexType>

    <xs:complexType name="CodomainElement">
        <xs:attribute type="ruleset:Type" name="type"/>
        <xs:attribute type="xs:anyURI" name="namespace"/>
    </xs:complexType>

    <xs:complexType name="DeclarationElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division" />
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Division">
        <xs:sequence>
            <xs:element type="ruleset:Label" minOccurs="1" maxOccurs="unbounded" name="label"/>
            <xs:element type="ruleset:SubdivisionByDateElement" minOccurs="0" maxOccurs="1" name="subdivisionByDate"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="xs:NMTOKEN" name="dates"/>
        <xs:attribute type="xs:string" name="scheme"/>
    </xs:complexType>

    <xs:simpleType name="DomainAttribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="description"/>
            <xs:enumeration value="digitalProvenance"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="technical"/>
            <xs:enumeration value="mets:div"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EditingElement">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
            <xs:element name="acquisitionStage" minOccurs="0" maxOccurs="unbounded" type="ruleset:AcquisitionStage"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Key">
        <xs:sequence>
            <xs:element name="label" minOccurs="1" maxOccurs="unbounded" type="ruleset:Label"/>
            <xs:element name="codomain" minOccurs="0" maxOccurs="1" type="ruleset:CodomainElement"/>
            <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            <xs:element name="pattern" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="preset" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="ruleset:DomainAttribute" name="domain" default="description"/>
    </xs:complexType>

    <xs:complexType name="Label">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="namespace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            </xs:sequence>
            <xs:attribute type="xs:anyURI" name="about"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="ruleset:Label"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="value"/>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence>
            <xs:element name="permit" minOccurs="0" maxOccurs="unbounded" type="ruleset:Rule"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="division"/>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs"/>
        <xs:attribute type="xs:nonNegativeInteger" name="maxOccurs"/>
        <xs:attribute type="ruleset:Unspecified" name="unspecified"/>
    </xs:complexType>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="declaration" minOccurs="1" maxOccurs="1" type="ruleset:DeclarationElement"/>
                <xs:element name="correlation" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="restriction" minOccurs="1" maxOccurs="unbounded" type="ruleset:Rule"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="editing" minOccurs="0" maxOccurs="1" type="ruleset:EditingElement"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="lang"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Setting">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:boolean" name="alwaysShowing" default="false"/>
        <xs:attribute type="xs:boolean" name="editable" default="true"/>
        <xs:attribute type="xs:boolean" name="excluded" default="false"/>
        <xs:attribute type="xs:boolean" name="multiline" default="false"/>
    </xs:complexType>

    <xs:complexType name="SubdivisionByDateElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division"/>
        </xs:sequence>
        <xs:attribute name="yearBegin">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="--((0[1-9]|1[0-2])-([01][1-9]|10|2[0-8]))|((0[13-9]|1[0-2])-(29|30))|((0[13578]|1[0-2])-31)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="anyURI"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Unspecified">
        <xs:restriction base="xs:string">
            <xs:enumeration value="unrestricted"/>
            <xs:enumeration value="forbidden"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== kitodo/kitodo-production/Kitodo/src/test/resources/rulesets/newspaper.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ../../../../../Kitodo-DataEditor/src/test/resources/ruleset.xsd">
    <declaration>
        <division id="Newspaper" processTitle="'Zeitung_'" use="createChildrenWithCalendar">
            <label>Newspaper ‹complete edition›</label>
            <label lang="de">Zeitung ‹Gesamtausgabe›</label>
            <subdivisionByDate>
                <division id="NewspaperYear" dates="ORDERLABEL" scheme="yyyy">
                    <label>Year’s issues ‹newspaper›</label>
                    <label lang="de">Jahrgang ‹Zeitung›</label>
                </division>
                <division id="NewspaperMonth" dates="ORDERLABEL" scheme="M">
                    <label>Month’s issues ‹newspaper›</label>
                    <label lang="de">Monat ‹Zeitung›</label>
                </division>
                <division id="NewspaperDay" dates="ORDERLABEL" scheme="d">
                    <label>Day’s issues ‹newspaper›</label>
                    <label lang="de">Tag ‹Zeitung›</label>
                </division>
            </subdivisionByDate>
        </division>
        <division id="Season">
            <label>season</label>
            <subdivisionByDate yearBegin="--07-01">
                <division dates="ORDERLABEL" id="SeasonYear"
                    scheme="yyyy/yyyy">
                    <label>Year’s issues ‹season›</label>
                </division>
                <division dates="ORDERLABEL" id="SeasonMonth"
                    scheme="yyyy-MM">
                    <label>Month’s issues ‹season›</label>
                </division>
                <division dates="ORDERLABEL" id="SeasonDay"
                    scheme="yyyy-MM-dd">
                    <label>Day’s issues ‹season›</label>
                </division>
            </subdivisionByDate>
        </division>
        <division id="NewspaperIssue">
            <label>Issue ‹newspaper›</label>
            <label lang="de">Ausgabe ‹Zeitung›</label>
        </division>
        <key id="ORDERLABEL" domain="mets:div">
            <label>METS order label</label>
            <label lang="de">METS Reihenfolge-Etikett</label>
        </key>
        <key id="ShelfMark" domain="source">
            <label>Shelf mark</label>
            <label lang="de">Signatur</label>
        </key>
        <key id="ProcessTitle" use="processTitle">
            <label>Process title</label>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testFieldsWithMinOccursGreaterZeroAreAlwaysShown.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="test1">
            <label>Test 1</label>
        </key>
        <key id="test2">
            <label>Test 2</label>
        </key>
        <key id="test2options">
            <label>Test 2</label>
            <option value="opt1"/>
            <option value="opt2"/>
            <option value="opt3"/>
        </key>
    </declaration>
    <correlation>
        <restriction division="book">
            <permit key="test1" minOccurs="1"/>
            <permit key="test2" minOccurs="2"/>
            <permit key="test2options" minOccurs="2"/>
        </restriction>
    </correlation>
</ruleset>

=== kitodo/kitodo-production/Kitodo/src/test/resources/rulesets/ruleset_newspaper-migration-test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ../../../../../Kitodo-DataEditor/src/main/resources/ruleset.xsd">
    <declaration>
        <division id="Newspaper">
            <label>Newspaper</label>
            <label lang="de">Zeitung</label>
            <subdivisionByDate>
                <division id="NewspaperYear" dates="ORDERLABEL" scheme="yyyy">
                    <label>year</label>
                    <label lang="de">Jahr</label>
                </division>
                <division id="NewspaperMonth" dates="ORDERLABEL" scheme="yyyy-MM">
                    <label>month</label>
                    <label lang="de">Monat</label>
                </division>
                <division id="NewspaperDay" dates="ORDERLABEL" scheme="yyyy-MM-dd">
                    <label>day</label>
                    <label lang="de">Tag</label>
                </division>
            </subdivisionByDate>
        </division>
        <division id="PeriodicalIssue">
            <label>Issue</label>
            <label lang="de">Heft/Ausgabe</label>
        </division>
        <key id="ORDERLABEL" domain="mets:div">
            <label>METS order label</label>
            <label lang="de">METS Reihenfolge-Etikett</label>
        </key>
        <key id="PeriodicalIssue">
            <label>Name of Issue</label>
            <label lang="de">Ausgabenbezeichnung</label>
        </key>
        <key id="CurrentNo">
            <label>number of volume/issue (or year)</label>
            <label lang="de">Band-/Heft-Nummer (oder Jahr)</label>
        </key>
        <key id="TitleDocMain">
            <label>main title</label>
            <label lang="de">Haupttitel</label>
        </key>
        <key id="TitleDocMainShort">
            <label>main title (sorting)</label>
            <label lang="de">Haupttitel (Sortierung)</label>
        </key>
        <key id="singleDigCollection">
            <label>digital collection</label>
            <label lang="de">Digitale Sammlung</label>
        </key>
        <key id="TSL_ATS">
            <label>TSL/ATS</label>
        </key>
    </declaration>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testRulesAreCorrectlyMerged.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="personContributor">
            <label>Contributor (natural person)</label>
            <key id="dateOfBirth">
                <label>Date of birth</label>
                <codomain type="date"/>
            </key>
            <key id="dateOfDeath">
                <label>Date of death</label>
                <codomain type="date"/>
            </key>
            <key id="disambiguationAddition">
                <label>Disambiguation addition</label>
            </key>
            <key id="givenName">
                <label>Given name</label>
            </key>
            <key id="gndRecord">
                <label>GND record</label>
                <codomain type="anyURI"/>
            </key>
            <key id="role">
                <label>Role</label>
                <option value="author"><label>Author</label></option>
                <option value="censor"><label>Censor</label></option>
                <option value="composer"><label>Composer</label></option>
                <option value="editor"><label>Editor</label></option>
                <option value="involvedPerson"><label>Involved person</label></option>
                <option value="librettist"><label>Librettist</label></option>
                <option value="photographer"><label>Photographer</label></option>
                <option value="uninvolvedPerson"><label>Uninvolved person</label></option>
            </key>
            <key id="surname">
                <label>Surname</label>
            </key>
            <key id="ppn">
                <label>Local system ID</label>
            </key>
        </key>
    </declaration>
    <correlation>
        <restriction key="personContributor">
            <permit key="role" minOccurs="1"/>
            <permit key="gndRecord"/>
            <permit key="givenName"/>
            <permit key="surname"/>
            <permit key="disambiguationAddition"/>
        </restriction>
        <restriction division="book" unspecified="forbidden">
            <permit key="personContributor">
                <permit key="role" unspecified="forbidden">
                    <permit value="author"/>
                    <permit value="editor"/>
                </permit>
            </permit>
        </restriction>
    </correlation>
    <editing>
        <setting key="personContributor" alwaysShowing="true">
            <setting key="role" alwaysShowing="true"/>
            <setting key="gndRecord" alwaysShowing="true"/>
            <setting key="givenName" alwaysShowing="true"/>
            <setting key="surname" alwaysShowing="true"/>
        </setting>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testDisplaySettingsWithoutAcquisitionStage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="book">
            <label>Book</label>
        </division>
        <key id="testAlwaysShowing">
            <label>Test always showing</label>
        </key>
        <key id="testEditable">
            <label>Test editable</label>
        </key>
        <key id="testExcluded">
            <label>Test excluded</label>
        </key>
        <key id="testMultiline">
            <label>Test multi-line</label>
        </key>
        <key id="testAlwaysShowingEditable">
            <label>Test always showing</label>
        </key>
        <key id="testAlwaysShowingExcluded">
            <label>Test always showing</label>
        </key>
        <key id="testAlwaysShowingMultiline">
            <label>Test always showing</label>
        </key>
        <key id="testEditableExcluded">
            <label>Test always showing</label>
        </key>
        <key id="testEditableMultiline">
            <label>Test always showing</label>
        </key>
        <key id="testExcludedMultiline">
            <label>Test always showing</label>
        </key>
        <key id="testNestedSettings">
            <label>Test nested settings</label>
            <key id="testAlwaysShowing">
                <label>Test nested always showing</label>
            </key>
            <key id="testEditable">
                <label>Test nested editable</label>
            </key>
            <key id="testExcluded">
                <label>Test nested excluded</label>
            </key>
            <key id="testMultiline">
                <label>Test nested multi-line</label>
            </key>
        </key>
    </declaration>
    <editing>
        <setting key="testAlwaysShowing" alwaysShowing="true" />
        <setting key="testEditable" editable="false" />
        <setting key="testExcluded" excluded="true" />
        <setting key="testMultiline" multiline="true" />
        <setting key="testAlwaysShowingEditable" alwaysShowing="true" editable="false" />
        <setting key="testAlwaysShowingExcluded" alwaysShowing="true" excluded="true" />
        <setting key="testAlwaysShowingMultiline" alwaysShowing="true" multiline="true" />
        <setting key="testEditableExcluded" editable="false" excluded="true" />
        <setting key="testEditableMultiline" editable="false" multiline="true" />
        <setting key="testExcludedMultiline" excluded="true" multiline="true" />
        <setting key="testNestedSettings">
            <setting key="testAlwaysShowing" alwaysShowing="true" />
            <setting key="testEditable" editable="false" />
            <setting key="testExcluded" excluded="true" />
            <setting key="testMultiline" multiline="true" />
        </setting>
        <acquisitionStage name="Acquisition stage">
            <setting key="testAlwaysShowing" alwaysShowing="false" />
            <setting key="testEditable" editable="true" />
            <setting key="testExcluded" excluded="false" />
            <setting key="testMultiline" multiline="false" />
            <setting key="testAlwaysShowingEditable" alwaysShowing="false" editable="true" />
            <setting key="testAlwaysShowingExcluded" alwaysShowing="false" excluded="false" />
            <setting key="testAlwaysShowingMultiline" alwaysShowing="false" multiline="false" />
            <setting key="testEditableExcluded" editable="true" excluded="false" />
            <setting key="testEditableMultiline" editable="true" multiline="false" />
            <setting key="testExcludedMultiline" excluded="false" multiline="false" />
            <setting key="testNestedSettings">
                <setting key="testAlwaysShowing" alwaysShowing="false" />
                <setting key="testEditable" editable="true" />
                <setting key="testExcluded" excluded="false" />
                <setting key="testMultiline" multiline="false" />
            </setting>
        </acquisitionStage>
    </editing>
</ruleset>

=== kitodo/kitodo-production/Kitodo-DataEditor/src/test/resources/testReimportOfMetadataModes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ruleset.xsd">
    <declaration>
        <division id="division">
            <label>A division</label>
        </division>

        <!-- simple tests -->
        <key id="metadataToReplaceByDefault">
            <label>Metadata to replace by default</label>
        </key>

        <key id="metadataToReplaceExplicitly">
            <label>Metadata to replace explicitly</label>
        </key>

        <key id="metadataToAdd">
            <label>Metadata to add</label>
        </key>

        <key id="metadataToAddWithLimit">
            <label>Metadata to add with limit</label>
        </key>

        <key id="metadataThatIsNew">
            <label>Metadata that is new</label>
        </key>

        <key id="metadataToKeep">
            <label>Metadata to keep</label>
        </key>

        <!-- test acquisition stages -->
        <key id="metadataToAddDuringCreationAndKeepLater">
            <label>Metadata to add during creation and keep later</label>
        </key>

        <key id="metadataToKeepExceptInEditing">
            <label>Metadata to keep, except in editing</label>
        </key>
    </declaration>

    <correlation>
        <restriction division="division" unspecified="unrestricted">
            <permit key="metadataToAddWithLimit" maxOccurs="2"/>
        </restriction>
    </correlation>

    <editing>
        <setting key="metadataToAdd" reimport="add" />
        <setting key="metadataToAddWithLimit" reimport="add" />
        <setting key="metadataToReplaceExplicitly" reimport="replace" />
        <setting key="metadataToKeep" reimport="keep" />

        <!-- test acquisition stages -->
        <setting key="metadataToAddDuringCreationAndKeepLater" reimport="keep" />
        <setting key="metadataToKeepExceptInEditing" reimport="keep" />
        
        <acquisitionStage name="create">
            <setting key="metadataToAddDuringCreationAndKeepLater" reimport="add" />
        </acquisitionStage>

        <acquisitionStage name="edit">
            <setting key="metadataToKeepExceptInEditing" reimport="replace" />
        </acquisitionStage>
    </editing>
</ruleset>
